builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - files:
      - none*
release:
  prerelease: false

brews:
  - description: "Rotating credentials."
    github:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/rotator"
    test: system "#{bin}/rotator --help"
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - docker.pkg.github.com/chanzuckerberg/rotator/rotator:v{{.Version}}
    extra_files:
      - cmd
      - go.mod
      - go.sum
      - main.go
      - pkg
env_files:
  github_token: ~/.config/goreleaser/github_token
