version: 1
secrets:
  - name: test
    source:
      kind: snowflake
      emails: email1
      account: accountVal
      user: userVal
      role: roleVal
      schema: schemaVal
      database: databaseVal
      warehouse: warehouseVal
      private_key_path: private_key_pathVal
      private_key_password: private_key_passwordVal
    sinks:
      - kind: Databricks
        key_to_name:
          email: emailVal
          public_key: public_keyVal
          private_key: private_keyVal
