version: 1
secrets:
  - name: test
    source:
      kind: env
      name: TEST_ENV
    sinks:
      - kind: Heroku
        key_to_name:
          TEST_ENV: test_env
        AppIdentity: infinite-stream-28382
