name: release

on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types:
      - completed

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Increment Build Version
        run: ./.github/scripts/version-bump.sh
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CZIBUILDBOT_USERNAME }}
          password: ${{ secrets.CZIBUILDBOT_GITHUB_KEY }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.CZIBUILDBOT_GITHUB_KEY }}
